version: "3"
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg14
        environment:
            POSTGRES_PASSWORD: "password"
        volumes:
            - db-data:/var/lib/postgresql/data
            - .:/data
        ports:
            - "5439:5432"
volumes:
    db-data:
        driver: local